// Kirk's Definitive Red Wing Ranking — 2026 (14 pairs)
// allowedMonths: null = year-round. Otherwise array of month numbers (1-12) it's in rotation.
// idealTempF: [low, high] comfortable range.
// tags: used by the picker to match against today's conditions.
//   dry-only        avoid in rain/snow (oxfords, light leather, low-cut)
//   wet-ok          fine in rain
//   snow-ok         fine in snow / slush
//   hot-ok          good in genuine heat
//   cold-ok         good in genuine cold
//   dress           business/client appropriate
//   casual          everyday casual
//   statement       "when the vibe calls for it" boot, not an everyday default
//   shorts          the one pair that works with shorts

export const BOOTS = [
  {
    rank: 1,
    id: "3343-blacksmith",
    model: "3343",
    name: "Blacksmith – Copper Rough & Tough",
    leather: "Copper Rough & Tough",
    allowedMonths: null,
    idealTempF: [20, 85],
    tags: ["wet-ok", "casual", "dress"],
    signature: "Does everything well",
    limiter: "None",
    outfit: "This is the one boot that doesn't ask you to think twice: The Perfect Jean in Cowboy Wash, the Jockey Outdoor Luke Bryan Henley or a Hammer Made Custer, and the Iron & Resin Hunter Jacket if it's cool out. It goes from errands to dinner without changing anything else you're wearing.",
    matchKeywords: ["denim", "jeans", "dark denim", "raw denim", "henley", "flannel", "canvas jacket"],
  },
  {
    rank: 2,
    id: "3138-grey-chukka",
    model: "3138",
    name: "Grey Chukka – Rough & Tough",
    leather: "Grey Rough & Tough",
    allowedMonths: null,
    idealTempF: [30, 80],
    tags: ["wet-ok", "casual", "dress"],
    signature: "10-yr sentiment + versatility",
    limiter: "Lower collectibility",
    outfit: "Grey chukkas want a slightly dressed-up base: the Banana Republic Athletic Travel Pant or Big Star Union, a J.Crew Gauze Chambray or Brooks Brothers Button Down, and the Marine Layer Corbet Quilted Full Zip if it's cool. The Perfect Jean works too if you cuff them.",
    matchKeywords: ["chinos", "grey", "gray", "trousers", "chambray", "oxford shirt", "quarter-zip", "quarter zip", "blazer", "jeans"],
  },
  {
    rank: 3,
    id: "4603-eg-copper-remix",
    model: "4603",
    name: "EG Copper Remix Oxford",
    leather: "Copper Remix",
    allowedMonths: null,
    idealTempF: [40, 90],
    tags: ["dry-only", "casual", "dress", "hot-ok"],
    signature: "Cool factor + collectibility",
    limiter: "Weather-restricted",
    outfit: "Keep it dry-weather and let the boot be the statement: Uniqlo Selvedge Jeans or The Perfect Jean, a Marine Layer Banks Tee under the Marine Layer Pacifica Stretch Twill Overshirt, minimal jewelry. Don't compete with it — everything else should be quiet.",
    matchKeywords: ["denim", "slim denim", "cropped trousers", "tee", "t-shirt", "overshirt", "copper"],
  },
  {
    rank: 4,
    id: "877-classic-moc",
    model: "877",
    name: "Classic Moc 8\" – Oro Legacy",
    leather: "Oro Legacy",
    allowedMonths: [10, 11, 12, 1, 2, 3, 4],
    idealTempF: [15, 55],
    tags: ["wet-ok", "snow-ok", "cold-ok", "casual"],
    signature: "Iconic silhouette, collectible",
    limiter: "Oct–Apr only",
    outfit: "This is your plaid/flannel/denim uniform boot. The JCRT Sunshine Rock Flannel or Carhartt Midweight Plaid, the Iron & Resin Hunter Jacket over top, Dearborn Long Ryder Jeans with a slight break. Let the tall moc toe show — no need to cuff heavily.",
    matchKeywords: ["flannel", "plaid", "waxed canvas", "wool jacket", "denim", "straight-leg", "jeans"],
  },
  {
    rank: 5,
    id: "8209-norway-moc",
    model: "8209",
    name: "Norway Moc – Oro Russet",
    leather: "Oro Russet",
    allowedMonths: [11, 12, 1, 2, 3],
    idealTempF: [-10, 40],
    tags: ["snow-ok", "cold-ok", "wet-ok", "casual"],
    signature: "Winter dominance",
    limiter: "8-month bench time",
    outfit: "Full winter mode: the Warrior Butter Pullover Hoodie or Hammer Made Tomas Crewneck under the Canada Goose Chateau Parka, Dearborn Long Ryder Jeans, wool socks showing at the cuff. This boot is doing the hard work — dress warm around it.",
    matchKeywords: ["wool sweater", "sweater", "flannel jacket", "denim", "canvas pants", "wool socks"],
  },
  {
    rank: 6,
    id: "9422-beckman",
    model: "9422",
    name: "Beckman – Excalibur Cigar",
    leather: "Excalibur Cigar",
    allowedMonths: null,
    idealTempF: [25, 75],
    tags: ["dress", "casual", "wet-ok"],
    signature: "Business/client confidence",
    limiter: "Less casual-brewery",
    outfit: "Your client-facing outfit: the Banana Republic Athletic Travel Pant or Big Star Union, a Brooks Brothers Button Down or the Brooks Brothers PBDC Checked Shirt, and a clean overcoat. Polished but not stiff — this boot carries the whole look.",
    matchKeywords: ["tailored trousers", "trousers", "dark chinos", "chinos", "button-down", "button down", "sport coat", "overcoat", "dress shirt"],
  },
  {
    rank: 7,
    id: "8089-iron-ranger",
    model: "8089",
    name: "Iron Ranger – Oro Legacy",
    leather: "Oro Legacy",
    allowedMonths: null,
    idealTempF: [25, 70],
    tags: ["dress", "statement", "wet-ok"],
    signature: "Iconic, statement-outfit king",
    limiter: "Cap toe vs. slacks",
    outfit: "The JCRT London Calling Plaid or Joseph Abboud Grey / Field Tan Plaid with dark Dearborn Long Ryder Jeans — exactly like last night. Add the Iron & Resin Rambler Jacket over top. This is a boot you deploy on purpose, not a daily default.",
    matchKeywords: ["plaid", "dark denim", "denim", "cardigan", "field jacket"],
  },
  {
    rank: 8,
    id: "3110-eg-black-multi",
    model: "3110",
    name: "EG Black Multi Oxford",
    leather: "Black Multi",
    allowedMonths: null,
    idealTempF: [35, 75],
    tags: ["dry-only", "dress", "casual"],
    signature: "Go-to for black, funky-dressy edge",
    limiter: "Black-forward outfits only",
    outfit: "Your go-to whenever black is the plan. For everyday, Mugsy Mags in black with the Hammer Made Black / Blue / Red / Grey Plaid worn open as an overshirt, minimal contrast. For a dressier night out, it holds up just as well with tailored black trousers and a blazer — cool-dressy rather than stiff-dressy, which is exactly its lane.",
    matchKeywords: ["black", "charcoal", "denim", "grey overshirt", "gray overshirt", "overshirt", "monochrome", "tailored trousers", "blazer", "funky", "dressy", "cool dressy"],
  },
  {
    rank: 9,
    id: "8079-abilene-moc",
    model: "8079",
    name: "Shop Moc Oxford – Hawthorne Abilene",
    leather: "Hawthorne Abilene",
    allowedMonths: [5, 6, 7, 8, 9],
    idealTempF: [65, 100],
    tags: ["hot-ok", "shorts", "casual", "dry-only"],
    signature: "Shorts-compatible pair",
    limiter: "Warm/dry only",
    outfit: "A pair that's genuinely fine with shorts: 01.algo Performance Shorts or Waggle Shorts, a Kuhl Short Sleeve or Quince Linen Natural up top, no socks showing. Light and low-key — let the Abilene leather catch the light.",
    matchKeywords: ["shorts", "chino shorts", "linen shorts", "linen", "tee", "t-shirt", "camp collar"],
  },
  {
    rank: 10,
    id: "3604-weekender",
    model: "3604",
    name: "Weekender Oxford – Copper Rough & Tough",
    leather: "Copper Rough & Tough",
    allowedMonths: [4, 5, 6, 7, 8, 9, 10],
    idealTempF: [55, 90],
    tags: ["hot-ok", "shorts", "casual", "dry-only"],
    signature: "Rising star, favorite leather, shorts-compatible too",
    limiter: "Unproven, less substantial",
    outfit: "Warm-weather low-key: Waggle Shorts or rolled Uniqlo Selvedge Jeans, with the Quince Linen Navy or a J.Crew Gauze Chambray worn untucked. This boot wants to look effortless, so don't overdress around it.",
    matchKeywords: ["chinos", "lightweight denim", "denim", "linen", "oxford shirt", "untucked", "shorts"],
  },
  {
    rank: 11,
    id: "9215-oil-slick-chukka",
    model: "9215",
    name: "Oil Slick Chukka – Briar",
    leather: "Briar Oil Slick",
    allowedMonths: null,
    idealTempF: [30, 75],
    tags: ["casual", "dress", "wet-ok"],
    signature: "Business casual switch-up",
    limiter: "Lost \"fresh\" factor",
    outfit: "A dependable switch-up from the Beckman: Big Star Union or The Perfect Jean, a Brooks Brothers PBDC Checked Shirt or Marine Layer Corduroy Shirt, the Quince Hybrid Insulated Vest if it's cool. Understated and reliable, the veteran move.",
    matchKeywords: ["dark trousers", "trousers", "raw denim", "denim", "polo", "oxford shirt", "unstructured jacket"],
  },
  {
    rank: 12,
    id: "3194-chelsea",
    model: "3194",
    name: "Chelsea – Black Harness",
    leather: "Black Harness",
    allowedMonths: null,
    idealTempF: [35, 75],
    tags: ["dress", "dry-only", "casual"],
    signature: "Sleek, trend-aligned",
    limiter: "Black + orthotics",
    outfit: "Mugsy Mags in black or slim dark indigo denim, a Marine Layer Banks Tee, and the Canada Goose Chateau Parka over top on a cold night. The Chelsea silhouette wants a clean, minimal outfit built around it.",
    matchKeywords: ["black", "dark indigo denim", "indigo", "denim", "tee", "t-shirt", "white tee", "longline coat", "coat"],
  },
  {
    rank: 13,
    id: "4070-postman",
    model: "4070",
    name: "Postman Oxford – Black",
    leather: "Black",
    allowedMonths: null,
    idealTempF: [30, 75],
    tags: ["dress", "dry-only"],
    signature: "Reliable dress option",
    limiter: "Mental \"postman\" turn-off",
    outfit: "Reach for this when the occasion is genuinely dressy: the Banana Republic Athletic Travel Pant or tailored chinos, a Brooks Brothers Button Down, no tie needed. Classic and safe when you need safe.",
    matchKeywords: ["suit trousers", "trousers", "tailored chinos", "chinos", "dress shirt", "crisp shirt", "suit", "black"],
  },
  {
    rank: 14,
    id: "3928-irish-setter",
    model: "3928",
    name: "Irish Setter Pull-On – Brown",
    leather: "Brown",
    allowedMonths: null,
    idealTempF: [10, 90],
    tags: ["wet-ok", "snow-ok", "casual", "cold-ok"],
    signature: "Grab-and-go comfort",
    limiter: "Not Heritage, low cool factor",
    outfit: "Yardwork and errands: whatever's already in the laundry pile. Dearborn Long Ryder Jeans and the Carhartt Midweight Plaid, or the Carhartt Rain Defender Insulated Vest if it's damp — comfort over style is the whole point today.",
    matchKeywords: ["work pants", "beat-up denim", "denim", "old flannel", "flannel", "hoodie", "sweatpants"],
  },
];
